/**
 * Contract addresses and ABIs.
 *
 * ABIs are generated by Foundry during `forge build` and should be
 * copied from contracts/out/[Contract].sol/[Contract].json.
 *
 * Addresses are populated after deployment — update from .env or
 * hardcode after mainnet deploy.
 */

// ── Addresses ──
// These read from environment variables set in .env.local

export const RITUAL_TOKEN_ADDRESS =
  (process.env.NEXT_PUBLIC_RITUAL_TOKEN_ADDRESS || "") as `0x${string}`;

export const BONDING_CURVE_ADDRESS =
  (process.env.NEXT_PUBLIC_BONDING_CURVE_ADDRESS || "") as `0x${string}`;

export const SUMMONING_ENGINE_ADDRESS =
  (process.env.NEXT_PUBLIC_SUMMONING_ENGINE_ADDRESS || "") as `0x${string}`;

export const ELDER_ARTIFACTS_ADDRESS =
  (process.env.NEXT_PUBLIC_ELDER_ARTIFACTS_ADDRESS || "") as `0x${string}`;

// ── ABIs ──
// Using parseAbi from viem so wagmi v2 hooks receive properly typed ABI objects.

import { parseAbi } from "viem";

export const RITUAL_TOKEN_ABI = parseAbi([
  "function balanceOf(address) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
]);

export const BONDING_CURVE_ABI = parseAbi([
  "function mint(uint256 minTokens) payable",
  "function getCurrentPrice() view returns (uint256)",
  "function getEstimatedCost(uint256 tokenAmount) view returns (uint256)",
]);

export const SUMMONING_ENGINE_ABI = parseAbi([
  "function commitRitual(uint256 amount)",
  "function claimReward(uint256 epochId)",
  "function currentEpochId() view returns (uint256)",
  "function contributions(uint256 epochId, address wallet) view returns (uint256)",
  "function getCurrentPhase() view returns (uint8)",
  "function lastSacrificeTime(address) view returns (uint256)",
  "event RitualSacrifice(uint256 indexed epochId, address indexed wallet, uint256 amount, uint256 totalCommitted)",
]);

export const ELDER_ARTIFACTS_ABI = parseAbi([
  "function balanceOf(address account, uint256 id) view returns (uint256)",
  "function balanceOfBatch(address[] accounts, uint256[] ids) view returns (uint256[])",
  "function uri(uint256 tokenId) view returns (string)",
]);
