/**
 * Contract addresses and ABIs.
 *
 * ABIs are generated by Foundry during `forge build` and should be
 * copied from contracts/out/[Contract].sol/[Contract].json.
 *
 * Addresses are populated after deployment — update from .env or
 * hardcode after mainnet deploy.
 */

// ── Addresses ──
// These read from environment variables set in .env.local

export const RITUAL_TOKEN_ADDRESS =
  (process.env.NEXT_PUBLIC_RITUAL_TOKEN_ADDRESS || "") as `0x${string}`;

export const MINTING_CURVE_ADDRESS =
  (process.env.NEXT_PUBLIC_MINTING_CURVE_ADDRESS || "") as `0x${string}`;

export const SUMMONING_ENGINE_ADDRESS =
  (process.env.NEXT_PUBLIC_SUMMONING_ENGINE_ADDRESS || "") as `0x${string}`;

export const ELDER_ARTIFACTS_ADDRESS =
  (process.env.NEXT_PUBLIC_ELDER_ARTIFACTS_ADDRESS || "") as `0x${string}`;

export const ELDRITCH_GLYPHS_ADDRESS =
  (process.env.NEXT_PUBLIC_ELDRITCH_GLYPHS_ADDRESS || "") as `0x${string}`;

// ── ABIs ──
// Using parseAbi from viem so wagmi v2 hooks receive properly typed ABI objects.

import { parseAbi } from "viem";

export const RITUAL_TOKEN_ABI = parseAbi([
  "function balanceOf(address) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function totalSupply() view returns (uint256)",
]);

export const MINTING_CURVE_ABI = parseAbi([
  "function mint(uint256 minTokens) payable",
  "function getCurrentPrice() view returns (uint256)",
  "function getEstimatedCost(uint256 tokenAmount) view returns (uint256)",
]);

export const SUMMONING_ENGINE_ABI = parseAbi([
  // Core gameplay
  "function commitRitual(uint256 amount)",
  "function resolveEpoch()",
  "function claimReward(uint256 epochId)",
  "function claimGlyphs(uint256 epochId) returns (uint256 numClaimed)",
  // Views
  "function currentEpochId() view returns (uint256)",
  "function getCurrentPhase() view returns (uint8)",
  "function getEpoch(uint256 epochId) view returns (uint256 oldOneId, uint256 threshold, uint256 totalCommitted, uint256 gatheringStart, uint256 ritualStart, uint256 ritualEnd, bool successful, bool resolved, uint256 participantCount)",
  "function getContribution(uint256 epochId, address wallet) view returns (uint256)",
  "function getContributors(uint256 epochId) view returns (address[])",
  "function nextThreshold() view returns (uint256)",
  "function lastSacrificeTime(address) view returns (uint256)",
  "function contributions(uint256 epochId, address wallet) view returns (uint256)",
  "function lifetimeContribution(address wallet) view returns (uint256)",
  "function glyphsClaimedCount(uint256 epochId, address wallet) view returns (uint256)",
  "function rewardClaimed(uint256 epochId, address wallet) view returns (bool)",
  // Events
  "event EpochStarted(uint256 indexed epochId, uint256 oldOneId, uint256 threshold, uint256 gatheringStart)",
  "event RitualSacrifice(uint256 indexed epochId, address indexed wallet, uint256 amount, uint256 totalCommitted)",
  "event EpochResolved(uint256 indexed epochId, bool successful, uint256 totalBurned)",
  "event RewardClaimed(uint256 indexed epochId, address indexed wallet, uint256 tierId)",
  "event GlyphsClaimRequested(uint256 indexed epochId, address indexed wallet, uint256 numGlyphs, uint256 cumulativeContribution)",
]);

export const ELDER_ARTIFACTS_ABI = parseAbi([
  "function balanceOf(address account, uint256 id) view returns (uint256)",
  "function balanceOfBatch(address[] accounts, uint256[] ids) view returns (uint256[])",
  "function uri(uint256 tokenId) view returns (string)",
]);

export const ELDRITCH_GLYPHS_ABI = parseAbi([
  // Views
  "function glyphCount(address wallet) view returns (uint256)",
  "function totalMinted() view returns (uint256)",
  "function getGlyphData(uint256 tokenId) view returns (uint8 tier, uint8 runeIndex, uint8 loreIndex, uint256 epochId, address originalRecipient)",
  "function balanceOf(address account, uint256 id) view returns (uint256)",
  "function uri(uint256 tokenId) view returns (string)",
  // Events
  "event GlyphsBatchRequested(uint256 indexed requestId, address indexed recipient, uint256 epochId, uint256 numGlyphs, uint256 cumulativeContribution)",
  "event GlyphMinted(uint256 indexed tokenId, address indexed recipient, uint8 tier, uint8 runeIndex, uint8 loreIndex, uint256 epochId)",
  "event GlyphsBatchMinted(uint256 indexed requestId, address indexed recipient, uint256 epochId, uint256 numGlyphs)",
]);
